const webpack = require('webpack')
const MiniCssEctractPlugin = require('mini-css-extract-plugin');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const OptimilizeCssnanoPlugin = require('@intervolga/optimize-cssnano-plugin')
const { WebpackManifestPlugin } = require('webpack-manifest-plugin');
const { removeEmpty } = require('webpack-config-utils');
const path = require("path");
const { fromRoot, ifProd, ifDev } = require("./scripts/utils");

const styleLoader = {
  loader: 'style-loader'
}
const getCssLoader = (options) => ({
  loader: 'css-loader',
  options: {
    modules: {
      localsConvention: 'camelCase',
    },
    importLoaders: 1,
    sourceMap: true,
    ...options
  }
})
const postcssLoader = {
  loader: 'postcss-loader',
  options: {
    ident: 'postcss',
    sourceMap: true,
    plugins: () => [
      require('postcss-flexbugs-fixes'),
      require('autoprefixer')({
        overrideBrowserslist: [
          '>1%',
          'last 4 versions',
          'Firefox ESR',
          'not ie < 9',
        ],
        flexbox: 'no-2009'
      })
    ]
  }
}

module.exports = removeEmpty({
  mode: ifProd('production', 'development'),
  context: path.resolve(__dirname, 'client'),
  entry: "./index.js",
  output: {
    path: path.join(__dirname, "client/.build"),
    filename: "bundle.js"
  },
  module: {
    rules: [
      {
        oneOf: [
          {
            test: /\.(js|tsx|ts)$/,
            include: fromRoot('client'),
            exclude: /node_modules/,
            loader: "babel-loader",
            options: {
              cacheDirectory: true,
              ...(require(fromRoot('.babelrc.js')))
            }
          },
          {
            test: [/\.bmp$/, /\.gif$/, /\.jep?g$/, /\.png$/],
            exclude: /node_modules/,
            loader: "url-loader",
            options: {
              limit: 100000,
              name: 'assets/[name].[ext]'
            }
          },
          {
            test: /\.module\.css$/,
            use: [
              ifProd(MiniCssEctractPlugin.loader, styleLoader),
              getCssLoader({ module: true }),
              postcssLoader,
            ]
          },
          {
            test: /\.scss$/,
            use: [
              ifProd(MiniCssEctractPlugin.loader, styleLoader),
              getCssLoader({ module: false }),
              {
                loader: 'sass-loader',
                options: {
                  sourceMap: true,
                }
              }
            ]
          },
          {
            exclude: [
              /\.(js|tsx|ts)$/,
              /\.html$/,
              /\.json$/,
              /\.ejs$/,
              /\.mjs$/,
              /node_modules/,
            ],
            loader: 'file-loader',
            options: {
              name: 'assets/[name].[ext]'
            }
          }
        ].filter(Boolean)
      },
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.CLIENT_PORT': JSON.stringify(process.env.CLIENT_PORT),
      'process.env.PORT': JSON.stringify(process.env.PORT),
    }),
    new webpack.IgnorePlugin({ resourceRegExp: /^\.locale$/, contextRegExp: /moment$/ }),
    // // 避免由于模块路径大小写问题引起的错误
    ifDev(new CaseSensitivePathsPlugin()),
    ifProd(new MiniCssEctractPlugin()),
    ifProd(new OptimilizeCssnanoPlugin({
      sourceMap: true,
      cssnanoOptions: {
        preset: ['default']
      }
    })),
    new WebpackManifestPlugin({
      fileName: 'asset-manifest.json',
      writeToFileEmit: true,
      seed: {
        info: 'this file is generated by the webpack build. Do not modify directly.',
        assets: {},
      },
      generate(seed, files) {
        return files.reduce((manifest, asset) => {
          const {
            chunk: ignoredChunk,
            ...assetProps
          } = asset
          manifest.assets[asset.name] = {
            ...assetProps,
            path: assetProps.path.replace(/^auto\//, ''),
          }
          return manifest
        }, seed)
      }
    }),

  ].filter(Boolean),
  optimization: {
    moduleIds: 'named',
    emitOnErrors: false,
  },
  devtool: ifProd('source-map', 'cheap-module-source-map'),
  devServer: {
    client: {
      logging: 'info',
      overlay: false
    },
    static: {
      directory: path.join(__dirname, 'client/.build'),
    },
    allowedHosts: ['localhost'],
    host: 'localhost',
    hot: true,
    port: process.env.CLIENT_PORT || 7975,
  },
  performance: {
    hints: ifProd('warning', false),
    maxEntrypointSize: 1000000,
    maxAssetSize: 1000000,
  }


})
